### ISSUE TITLE
Migrate from Travis-CI

### ISSUE THREAD

**Issue by PMeira** [dss-extensions/OpenDSSDirect.jl#65]
I'm preparing a maintenance release in the coming days. With the recent Travis-CI changes, we need to move the testing process. 

Some options are:
- Move to GitHub actions. It seems easy enough and there are a bunch of Actions available on the marketplace (from https://github.com/julia-actions). There's also https://github.com/marketplace/actions/run-travis-yml but that's not really needed for Julia. Note that TagBot is installed as a GitHub action already. Downsides: more dependency on GitHub.
- Consolidate on AppVeyor, which nowadays supports MacOS too. Downsides: it's probably the slower solution (1 concurrent job).
- [Circle-CI](https://circleci.com/open-source/)? Downsides: credits for macOS are limited but should still be enough (they also changed how their billing works in 2020 but the open-source support is way better than the current Travis-CI scenario).
- GitLab also offers some free minutes.
- If the situation keeps changing in the future, we could move to self-hosted GitLab workers. I could easily host Windows and Linux workers, but not macOS. Downsides: potentially more maintenance, security concerns.

For ODD.jl, I'm considering just moving to GitHub actions since the tests are simple enough. I'll give it a try tomorrow.

By the way, support for Apple M1 seems overall limited for everything at the moment. We'll need to revisit that later. On the medium term, I suspect the main issue will be building the Pascal library. There is general support in FPC but also specific bugs. I imagine it probably won't be fully released for a while.

**Comment by kdheepak** [comment]
Thanks for sharing the update! The Julia community as well tend to have better support for GitHub actions. It does mean a greater dependency on GitHub but the value of convenience is high, so we should just go with that.

I can handle the Julia GitHub actions if you like. I've set it up a couple of other Julia package using GitHub actions, so it should be straightforward.

**Comment by PMeira** [comment]
> I can handle the Julia GitHub actions if you like. I've set it up a couple of other Julia package using GitHub actions, so it should be straightforward.

@kdheepak Sure, it'd be great if you could do it. So far I had the following (untested) but that'd still be missing building the docs:

<details>

```yaml
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  tests-and-coverage:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        julia-version: ["1", "1.0", "nightly"]
        julia-arch: [x64, x86]
        exclude:
          # Keep x86 only for Windows
          - os: macOS-latest
            julia-arch: x86
          - os: ubuntu-latest
            julia-arch: x86

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
          show-versioninfo: true

      - name: Run Pkg.build
        uses: julia-actions/julia-buildpkg@v1
        
      - name: Run Julia package tests
        uses: julia-actions/julia-runtest@v1
        with:
          coverage: true

      - uses: julia-actions/julia-processcoverage@v1

      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
```

</details>

Some comments:
- TagBot is able to use Documenter if a key is provided.
- For the Travis-CI recipe, we were pushing to both Coveralls and Codecov, but looks like Coveralls wasn't setup. We probably can skip it now.
- It seems people usually skip 32-bit tests altogether. Since, for us, testing the 32-bit builds did catch some issues in the past, it'd be nice to include them on either Windows or Linux.

And I forgot to mention why I opened an issue here first: the latest build took almost an hour in total ("Total time 56 min 5 sec").
